services:
  web:
    image: ghcr.io/moduluxsoft-cl/viajes-ead-web:${APP_VERSION:-latest}
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      NODE_ENV: qa
      APP_VERSION: ${APP_VERSION:-latest}
      EXPO_PUBLIC_USE_FIREBASE_EMULATORS: "true"
      EXPO_PUBLIC_FIREBASE_EMULATOR_HOST: "localhost"
      EXPO_PUBLIC_FIRESTORE_EMULATOR_PORT: "8080"
      EXPO_PUBLIC_AUTH_EMULATOR_PORT: "9099"
      EXPO_PUBLIC_FUNCTIONS_EMULATOR_PORT: "5001"
      EXPO_PUBLIC_PUBSUB_EMULATOR_PORT: "8085"
    depends_on:
      - firebase-emulators

  firebase-emulators:
    image: ghcr.io/moduluxsoft-cl/viajes-ead-firebase-emulators:${APP_VERSION:-latest}
    ports:
      - "4000:4000"
      - "9099:9099"
      - "8080:8080"
      - "5000:5000"
      - "8085:8085"
      - "5001:5001"
      - "4400:4400"